/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcessoNegadoRouteImport } from './routes/acesso-negado'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTarefasRouteImport } from './routes/_app/tarefas'
import { Route as AppLicencasRouteImport } from './routes/_app/licencas'
import { Route as AppFolgasRouteImport } from './routes/_app/folgas'
import { Route as AppFeriasRouteImport } from './routes/_app/ferias'
import { Route as AppFaltasRouteImport } from './routes/_app/faltas'
import { Route as AppEscalasRouteImport } from './routes/_app/escalas'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppColaboradoresRouteImport } from './routes/_app/colaboradores'
import { Route as AppAlertasRouteImport } from './routes/_app/alertas'
import { Route as AppAgendamentosRouteImport } from './routes/_app/agendamentos'
import { Route as ApiPublicHooksSyncFaltasRouteImport } from './routes/api/public/hooks/sync-faltas'
import { Route as ApiPublicFeriasDecisaoRouteImport } from './routes/api/public/ferias/decisao'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoNegadoRoute = AcessoNegadoRouteImport.update({
  id: '/acesso-negado',
  path: '/acesso-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTarefasRoute = AppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AppRoute,
} as any)
const AppLicencasRoute = AppLicencasRouteImport.update({
  id: '/licencas',
  path: '/licencas',
  getParentRoute: () => AppRoute,
} as any)
const AppFolgasRoute = AppFolgasRouteImport.update({
  id: '/folgas',
  path: '/folgas',
  getParentRoute: () => AppRoute,
} as any)
const AppFeriasRoute = AppFeriasRouteImport.update({
  id: '/ferias',
  path: '/ferias',
  getParentRoute: () => AppRoute,
} as any)
const AppFaltasRoute = AppFaltasRouteImport.update({
  id: '/faltas',
  path: '/faltas',
  getParentRoute: () => AppRoute,
} as any)
const AppEscalasRoute = AppEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppColaboradoresRoute = AppColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendamentosRoute = AppAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksSyncFaltasRoute =
  ApiPublicHooksSyncFaltasRouteImport.update({
    id: '/api/public/hooks/sync-faltas',
    path: '/api/public/hooks/sync-faltas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFeriasDecisaoRoute = ApiPublicFeriasDecisaoRouteImport.update({
  id: '/api/public/ferias/decisao',
  path: '/api/public/ferias/decisao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agendamentos': typeof AppAgendamentosRoute
  '/alertas': typeof AppAlertasRoute
  '/colaboradores': typeof AppColaboradoresRoute
  '/dashboard': typeof AppDashboardRoute
  '/escalas': typeof AppEscalasRoute
  '/faltas': typeof AppFaltasRoute
  '/ferias': typeof AppFeriasRoute
  '/folgas': typeof AppFolgasRoute
  '/licencas': typeof AppLicencasRoute
  '/tarefas': typeof AppTarefasRoute
  '/api/public/ferias/decisao': typeof ApiPublicFeriasDecisaoRoute
  '/api/public/hooks/sync-faltas': typeof ApiPublicHooksSyncFaltasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agendamentos': typeof AppAgendamentosRoute
  '/alertas': typeof AppAlertasRoute
  '/colaboradores': typeof AppColaboradoresRoute
  '/dashboard': typeof AppDashboardRoute
  '/escalas': typeof AppEscalasRoute
  '/faltas': typeof AppFaltasRoute
  '/ferias': typeof AppFeriasRoute
  '/folgas': typeof AppFolgasRoute
  '/licencas': typeof AppLicencasRoute
  '/tarefas': typeof AppTarefasRoute
  '/api/public/ferias/decisao': typeof ApiPublicFeriasDecisaoRoute
  '/api/public/hooks/sync-faltas': typeof ApiPublicHooksSyncFaltasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/acesso-negado': typeof AcessoNegadoRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/agendamentos': typeof AppAgendamentosRoute
  '/_app/alertas': typeof AppAlertasRoute
  '/_app/colaboradores': typeof AppColaboradoresRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/escalas': typeof AppEscalasRoute
  '/_app/faltas': typeof AppFaltasRoute
  '/_app/ferias': typeof AppFeriasRoute
  '/_app/folgas': typeof AppFolgasRoute
  '/_app/licencas': typeof AppLicencasRoute
  '/_app/tarefas': typeof AppTarefasRoute
  '/api/public/ferias/decisao': typeof ApiPublicFeriasDecisaoRoute
  '/api/public/hooks/sync-faltas': typeof ApiPublicHooksSyncFaltasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-negado'
    | '/login'
    | '/recuperar'
    | '/reset-password'
    | '/agendamentos'
    | '/alertas'
    | '/colaboradores'
    | '/dashboard'
    | '/escalas'
    | '/faltas'
    | '/ferias'
    | '/folgas'
    | '/licencas'
    | '/tarefas'
    | '/api/public/ferias/decisao'
    | '/api/public/hooks/sync-faltas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-negado'
    | '/login'
    | '/recuperar'
    | '/reset-password'
    | '/agendamentos'
    | '/alertas'
    | '/colaboradores'
    | '/dashboard'
    | '/escalas'
    | '/faltas'
    | '/ferias'
    | '/folgas'
    | '/licencas'
    | '/tarefas'
    | '/api/public/ferias/decisao'
    | '/api/public/hooks/sync-faltas'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/acesso-negado'
    | '/login'
    | '/recuperar'
    | '/reset-password'
    | '/_app/agendamentos'
    | '/_app/alertas'
    | '/_app/colaboradores'
    | '/_app/dashboard'
    | '/_app/escalas'
    | '/_app/faltas'
    | '/_app/ferias'
    | '/_app/folgas'
    | '/_app/licencas'
    | '/_app/tarefas'
    | '/api/public/ferias/decisao'
    | '/api/public/hooks/sync-faltas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AcessoNegadoRoute: typeof AcessoNegadoRoute
  LoginRoute: typeof LoginRoute
  RecuperarRoute: typeof RecuperarRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicFeriasDecisaoRoute: typeof ApiPublicFeriasDecisaoRoute
  ApiPublicHooksSyncFaltasRoute: typeof ApiPublicHooksSyncFaltasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-negado': {
      id: '/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof AcessoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tarefas': {
      id: '/_app/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AppTarefasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/licencas': {
      id: '/_app/licencas'
      path: '/licencas'
      fullPath: '/licencas'
      preLoaderRoute: typeof AppLicencasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/folgas': {
      id: '/_app/folgas'
      path: '/folgas'
      fullPath: '/folgas'
      preLoaderRoute: typeof AppFolgasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ferias': {
      id: '/_app/ferias'
      path: '/ferias'
      fullPath: '/ferias'
      preLoaderRoute: typeof AppFeriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faltas': {
      id: '/_app/faltas'
      path: '/faltas'
      fullPath: '/faltas'
      preLoaderRoute: typeof AppFaltasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/escalas': {
      id: '/_app/escalas'
      path: '/escalas'
      fullPath: '/escalas'
      preLoaderRoute: typeof AppEscalasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colaboradores': {
      id: '/_app/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AppColaboradoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alertas': {
      id: '/_app/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agendamentos': {
      id: '/_app/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AppAgendamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/sync-faltas': {
      id: '/api/public/hooks/sync-faltas'
      path: '/api/public/hooks/sync-faltas'
      fullPath: '/api/public/hooks/sync-faltas'
      preLoaderRoute: typeof ApiPublicHooksSyncFaltasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ferias/decisao': {
      id: '/api/public/ferias/decisao'
      path: '/api/public/ferias/decisao'
      fullPath: '/api/public/ferias/decisao'
      preLoaderRoute: typeof ApiPublicFeriasDecisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgendamentosRoute: typeof AppAgendamentosRoute
  AppAlertasRoute: typeof AppAlertasRoute
  AppColaboradoresRoute: typeof AppColaboradoresRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEscalasRoute: typeof AppEscalasRoute
  AppFaltasRoute: typeof AppFaltasRoute
  AppFeriasRoute: typeof AppFeriasRoute
  AppFolgasRoute: typeof AppFolgasRoute
  AppLicencasRoute: typeof AppLicencasRoute
  AppTarefasRoute: typeof AppTarefasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendamentosRoute: AppAgendamentosRoute,
  AppAlertasRoute: AppAlertasRoute,
  AppColaboradoresRoute: AppColaboradoresRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEscalasRoute: AppEscalasRoute,
  AppFaltasRoute: AppFaltasRoute,
  AppFeriasRoute: AppFeriasRoute,
  AppFolgasRoute: AppFolgasRoute,
  AppLicencasRoute: AppLicencasRoute,
  AppTarefasRoute: AppTarefasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AcessoNegadoRoute: AcessoNegadoRoute,
  LoginRoute: LoginRoute,
  RecuperarRoute: RecuperarRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicFeriasDecisaoRoute: ApiPublicFeriasDecisaoRoute,
  ApiPublicHooksSyncFaltasRoute: ApiPublicHooksSyncFaltasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
